# Generated by Django 4.2.5 on 2023-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Imagen', models.ImageField(upload_to='portfolio/images/')),
                ('URL', models.URLField(blank=True)),
            ],
        ),
    ]
