# Generated by Django 4.2.5 on 2023-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Descripcion',
            field=models.TextField(max_length=2500),
        ),
    ]
